[package]
name = "nomangle"
version = "0.1.0"
authors = ["adwait1-g <adwait.gautham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
